spring.application.name=smart-task-scheduler-api
# H2 Database
spring.datasource.url=jdbc:h2:mem:smart_scheduler
spring.datasource.username=admin
spring.datasource.password=admin
# Configuration
spring.data.web.pageable.one-indexed-parameters=true